//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutozaphastiKulckov.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderComposition
    {
        public int id { get; set; }
        public int IdOrder { get; set; }
        public string ProductArticle { get; set; }
        public int CountOrder { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
