//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutozaphastiKulckov.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderComposition = new HashSet<OrderComposition>();
        }
    
        public int id { get; set; }
        public System.DateTime Create_data { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int IdPickUpPount { get; set; }
        public int idClient { get; set; }
        public int CodeForGet { get; set; }
        public int Idstatus { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual PickUpPoint PickUpPoint1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderComposition> OrderComposition { get; set; }
    }
}
